# Prometheus scrape configuration for Video Transcriber
# Add this to your existing prometheus.yml

# Video Transcriber application metrics
scrape_configs:
  - job_name: 'video-transcriber'
    static_configs:
      - targets: ['video-transcriber-app:5000']  # Adjust hostname/port as needed
    metrics_path: '/monitoring/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'video-transcriber-health'
    static_configs:
      - targets: ['video-transcriber-app:5000']
    metrics_path: '/monitoring/health'
    scrape_interval: 60s

  # If using separate metrics port
  - job_name: 'video-transcriber-metrics'
    static_configs:
      - targets: ['video-transcriber-app:8000']  # If metrics on separate port
    metrics_path: '/metrics'
    scrape_interval: 30s

# Example rule groups for alerting
rule_files:
  - "video_transcriber_alerts.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
